/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SearchRouteImport } from './routes/search'
import { Route as MatchRouteImport } from './routes/match'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProfileIndexRouteImport } from './routes/profile.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as SchoolOnboardingRouteImport } from './routes/school.onboarding'
import { Route as SchoolDashboardRouteImport } from './routes/school.dashboard'
import { Route as ProviderIdRouteImport } from './routes/provider.$id'
import { Route as ProfileSavedRouteImport } from './routes/profile.saved'
import { Route as ProfileHistoryRouteImport } from './routes/profile.history'
import { Route as ClassIdRouteImport } from './routes/class.$id'
import { Route as BookIdRouteImport } from './routes/book.$id'
import { Route as AdminViewsRouteImport } from './routes/admin.views'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminSchoolsRouteImport } from './routes/admin.schools'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminLeadsRouteImport } from './routes/admin.leads'
import { Route as AdminClassesRouteImport } from './routes/admin.classes'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'

const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchRoute = MatchRouteImport.update({
  id: '/match',
  path: '/match',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const SchoolOnboardingRoute = SchoolOnboardingRouteImport.update({
  id: '/school/onboarding',
  path: '/school/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const SchoolDashboardRoute = SchoolDashboardRouteImport.update({
  id: '/school/dashboard',
  path: '/school/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ProviderIdRoute = ProviderIdRouteImport.update({
  id: '/provider/$id',
  path: '/provider/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileSavedRoute = ProfileSavedRouteImport.update({
  id: '/profile/saved',
  path: '/profile/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileHistoryRoute = ProfileHistoryRouteImport.update({
  id: '/profile/history',
  path: '/profile/history',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassIdRoute = ClassIdRouteImport.update({
  id: '/class/$id',
  path: '/class/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BookIdRoute = BookIdRouteImport.update({
  id: '/book/$id',
  path: '/book/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminViewsRoute = AdminViewsRouteImport.update({
  id: '/views',
  path: '/views',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSchoolsRoute = AdminSchoolsRouteImport.update({
  id: '/schools',
  path: '/schools',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLeadsRoute = AdminLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClassesRoute = AdminClassesRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => AdminRoute,
} as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/match': typeof MatchRoute
  '/search': typeof SearchRoute
  '/admin/classes': typeof AdminClassesRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/schools': typeof AdminSchoolsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/views': typeof AdminViewsRoute
  '/book/$id': typeof BookIdRoute
  '/class/$id': typeof ClassIdRoute
  '/profile/history': typeof ProfileHistoryRoute
  '/profile/saved': typeof ProfileSavedRoute
  '/provider/$id': typeof ProviderIdRoute
  '/school/dashboard': typeof SchoolDashboardRoute
  '/school/onboarding': typeof SchoolOnboardingRoute
  '/admin/': typeof AdminIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/match': typeof MatchRoute
  '/search': typeof SearchRoute
  '/admin/classes': typeof AdminClassesRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/schools': typeof AdminSchoolsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/views': typeof AdminViewsRoute
  '/book/$id': typeof BookIdRoute
  '/class/$id': typeof ClassIdRoute
  '/profile/history': typeof ProfileHistoryRoute
  '/profile/saved': typeof ProfileSavedRoute
  '/provider/$id': typeof ProviderIdRoute
  '/school/dashboard': typeof SchoolDashboardRoute
  '/school/onboarding': typeof SchoolOnboardingRoute
  '/admin': typeof AdminIndexRoute
  '/profile': typeof ProfileIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/match': typeof MatchRoute
  '/search': typeof SearchRoute
  '/admin/classes': typeof AdminClassesRoute
  '/admin/leads': typeof AdminLeadsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/schools': typeof AdminSchoolsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/admin/views': typeof AdminViewsRoute
  '/book/$id': typeof BookIdRoute
  '/class/$id': typeof ClassIdRoute
  '/profile/history': typeof ProfileHistoryRoute
  '/profile/saved': typeof ProfileSavedRoute
  '/provider/$id': typeof ProviderIdRoute
  '/school/dashboard': typeof SchoolDashboardRoute
  '/school/onboarding': typeof SchoolOnboardingRoute
  '/admin/': typeof AdminIndexRoute
  '/profile/': typeof ProfileIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/auth'
    | '/match'
    | '/search'
    | '/admin/classes'
    | '/admin/leads'
    | '/admin/login'
    | '/admin/schools'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/views'
    | '/book/$id'
    | '/class/$id'
    | '/profile/history'
    | '/profile/saved'
    | '/provider/$id'
    | '/school/dashboard'
    | '/school/onboarding'
    | '/admin/'
    | '/profile/'
    | '/.lovable/oauth/consent'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/match'
    | '/search'
    | '/admin/classes'
    | '/admin/leads'
    | '/admin/login'
    | '/admin/schools'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/views'
    | '/book/$id'
    | '/class/$id'
    | '/profile/history'
    | '/profile/saved'
    | '/provider/$id'
    | '/school/dashboard'
    | '/school/onboarding'
    | '/admin'
    | '/profile'
    | '/.lovable/oauth/consent'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/auth'
    | '/match'
    | '/search'
    | '/admin/classes'
    | '/admin/leads'
    | '/admin/login'
    | '/admin/schools'
    | '/admin/settings'
    | '/admin/users'
    | '/admin/views'
    | '/book/$id'
    | '/class/$id'
    | '/profile/history'
    | '/profile/saved'
    | '/provider/$id'
    | '/school/dashboard'
    | '/school/onboarding'
    | '/admin/'
    | '/profile/'
    | '/.lovable/oauth/consent'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  MatchRoute: typeof MatchRoute
  SearchRoute: typeof SearchRoute
  BookIdRoute: typeof BookIdRoute
  ClassIdRoute: typeof ClassIdRoute
  ProfileHistoryRoute: typeof ProfileHistoryRoute
  ProfileSavedRoute: typeof ProfileSavedRoute
  ProviderIdRoute: typeof ProviderIdRoute
  SchoolDashboardRoute: typeof SchoolDashboardRoute
  SchoolOnboardingRoute: typeof SchoolOnboardingRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/match': {
      id: '/match'
      path: '/match'
      fullPath: '/match'
      preLoaderRoute: typeof MatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/': {
      id: '/profile/'
      path: '/profile'
      fullPath: '/profile/'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/school/onboarding': {
      id: '/school/onboarding'
      path: '/school/onboarding'
      fullPath: '/school/onboarding'
      preLoaderRoute: typeof SchoolOnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/school/dashboard': {
      id: '/school/dashboard'
      path: '/school/dashboard'
      fullPath: '/school/dashboard'
      preLoaderRoute: typeof SchoolDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/provider/$id': {
      id: '/provider/$id'
      path: '/provider/$id'
      fullPath: '/provider/$id'
      preLoaderRoute: typeof ProviderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/saved': {
      id: '/profile/saved'
      path: '/profile/saved'
      fullPath: '/profile/saved'
      preLoaderRoute: typeof ProfileSavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/history': {
      id: '/profile/history'
      path: '/profile/history'
      fullPath: '/profile/history'
      preLoaderRoute: typeof ProfileHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/class/$id': {
      id: '/class/$id'
      path: '/class/$id'
      fullPath: '/class/$id'
      preLoaderRoute: typeof ClassIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/$id': {
      id: '/book/$id'
      path: '/book/$id'
      fullPath: '/book/$id'
      preLoaderRoute: typeof BookIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/views': {
      id: '/admin/views'
      path: '/views'
      fullPath: '/admin/views'
      preLoaderRoute: typeof AdminViewsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/schools': {
      id: '/admin/schools'
      path: '/schools'
      fullPath: '/admin/schools'
      preLoaderRoute: typeof AdminSchoolsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/leads': {
      id: '/admin/leads'
      path: '/leads'
      fullPath: '/admin/leads'
      preLoaderRoute: typeof AdminLeadsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/classes': {
      id: '/admin/classes'
      path: '/classes'
      fullPath: '/admin/classes'
      preLoaderRoute: typeof AdminClassesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminClassesRoute: typeof AdminClassesRoute
  AdminLeadsRoute: typeof AdminLeadsRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminSchoolsRoute: typeof AdminSchoolsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminViewsRoute: typeof AdminViewsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminClassesRoute: AdminClassesRoute,
  AdminLeadsRoute: AdminLeadsRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminSchoolsRoute: AdminSchoolsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminViewsRoute: AdminViewsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  MatchRoute: MatchRoute,
  SearchRoute: SearchRoute,
  BookIdRoute: BookIdRoute,
  ClassIdRoute: ClassIdRoute,
  ProfileHistoryRoute: ProfileHistoryRoute,
  ProfileSavedRoute: ProfileSavedRoute,
  ProviderIdRoute: ProviderIdRoute,
  SchoolDashboardRoute: SchoolDashboardRoute,
  SchoolOnboardingRoute: SchoolOnboardingRoute,
  ProfileIndexRoute: ProfileIndexRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
